spring.application.name=fit-match
spring.datasource.url=jdbc:h2:file:./myDB;DB_CLOSE_ON_EXIT=FALSE
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.continue-on-error=true

# הגדרות לשליחת מיילים אמיתיים דרך Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=the.your.email@gmail.com
# כאן שמים סיסמת אפליקציה מיוחדת שמייצרים בתוך חשבון הגוגל שלך (App Password)
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true