DROP INDEX IF EXISTS CONSTRAINT_94_INDEX_F;
DROP INDEX IF EXISTS uk_program_workout_status_program_sequence;
ALTER TABLE PROGRAM_WORKOUT_STATUS DROP CONSTRAINT IF EXISTS CONSTRAINT_94;
CREATE UNIQUE INDEX IF NOT EXISTS uk_program_workout_status_program_sequence
    ON PROGRAM_WORKOUT_STATUS(PROGRAM_ID, SEQUENCE);
